# Generated by Django 5.2.7 on 2025-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
