# Generated by Django 5.2.7 on 2025-11-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_livro_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
