# Generated by Django 5.2.7 on 2025-11-12 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_delete_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
